language: go
sudo: false
go:
  - 1.4.3
  - 1.5.1
  - tip
install:
  - go get golang.org/x/lint/golint
  - go get github.com/mattn/gom
  - gom -test install
script:
  - test -z "$(golint ./... | tee /dev/stderr)"
  - gom test -v ./...
  - gom test -v -bench .
matrix:
  allow_failures:
    - go: tip
